<?php

use WowApi\Request\Curl;

/**
 * Test class for Curl.
 * Generated by PHPUnit on 2011-07-31 at 16:50:08.
 */
class CurlTest extends AbstractRequestTest
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();

        if (!function_exists('curl_init')) {
            $this->markTestSkipped('Curl is not installed');
        }
    }

    /**
     * @todo Implement testMakeRequest().
     */
    public function testMakeRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    function getRequestAdaptor()
    {
        return new Curl();
    }
}
?>
