<?php

use WowApi\Request\Curl;

/**
 * Test class for Curl.
 * Generated by PHPUnit on 2011-07-31 at 16:50:08.
 */
class CurlTest extends AbstractRequestTest
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();

        if (!function_exists('curl_init')) {
            $this->markTestSkipped('Curl is not installed');
        }
    }

    public function testMakeRequest()
    {
        $client = new \WowApi\Client();
        $client->setRegion('us');
        $client->setRequest(new Curl($client));
        $client->getRequest()->makeRequest('http://us.blizzard.com/');
    }

    public function testMakeRequestToNonExistantPage()
    {
        $client = new \WowApi\Client();
        $client->setRegion('us');
        $client->setRequest(new Curl($client));
        $response = $client->getRequest()->makeRequest('http://us.blizzard.com/404');
        $this->assertEquals(404, $response['headers']['http_code']);
    }

    function getRequestAdaptor()
    {
        return new Curl();
    }
}
?>
